export { default as Switch } from './Switch.svelte';

export type SwitchProps = {
	value?: boolean | string;
	label?: string;
	design?: 'inner' | 'slider' | 'ios' | 'modern' | 'material' | 'multi' | 'neon' | 'flip' | 'pill';
	options?: string[];
	size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | number;
	color?: string;
	offColor?: string;
	colorScheme?: 'blue' | 'green' | 'red' | 'purple' | 'orange' | 'pink' | 'yellow' | 'indigo' | 'teal' | 'custom';
	disabled?: boolean;
	loading?: boolean;
	readonly?: boolean;
	showIcons?: boolean;
	onIcon?: string;
	offIcon?: string;
	animationDuration?: number;
	animationEasing?: string;
	ariaLabel?: string;
	ariaDescribedBy?: string;
	id?: string;
	name?: string;
	tabIndex?: number;
	labelPosition?: 'left' | 'right';
	rounded?: boolean;
	shadow?: boolean;
	outline?: boolean;
	onText?: string;
	offText?: string;
	helperText?: string;
	errorText?: string;
	required?: boolean;
	error?: boolean;
	darkMode?: boolean | 'auto';
	gradient?: boolean;
	gradientPreset?: 'sunset' | 'ocean' | 'forest' | 'berry' | 'fire' | 'custom';
	customGradient?: string;
	swipeToToggle?: boolean;
	swipeThreshold?: number;
	dir?: 'ltr' | 'rtl' | 'auto';
	pulse?: boolean;
	pulseColor?: string;
	pulseIntensity?: 'subtle' | 'normal' | 'strong';
	showSuccessAnimation?: boolean;
	showErrorAnimation?: boolean;
	successDuration?: number;
	hapticFeedback?: boolean;
	hapticPattern?: 'light' | 'medium' | 'heavy' | number[];
	skeleton?: boolean;
	skeletonAnimation?: 'shimmer' | 'pulse' | 'wave';
	tooltip?: string;
	tooltipPosition?: 'top' | 'bottom' | 'left' | 'right';
	tooltipDelay?: number;
	// v3.0.0
	flipFrontContent?: string;
	flipBackContent?: string;
	dragMomentum?: boolean;
	longPress?: boolean;
	longPressDuration?: number;
	confirmToggle?: boolean;
	confirmMessage?: string;
	onconfirm?: () => Promise<boolean>;
	onchange?: (payload: { value: boolean | string; checked: boolean }) => void;
	onfocus?: (payload: { event: FocusEvent }) => void;
	onblur?: (payload: { event: FocusEvent }) => void;
};
